version: "3.6"
services:
  service:
    build:
      context: .
      target: service
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    command: uvicorn openapi_server.main:app --host 0.0.0.0 --port 8080
