

[tool.black]
line-length = 88
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''

[tool.isort]
profile = "black"
skip = [
    '.eggs', '.git', '.hg', '.mypy_cache', '.nox', '.pants.d', '.tox',
    '.venv', '_build', 'buck-out', 'build', 'dist', 'node_modules', 'venv',
]
skip_gitignore = true

[tool.poetry]
name = "ds-caselaw-privileged-api"
version = "0.3.0"
description = ""
authors = ["David McKee <david.mckee@dxw.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10, <4"
fastapi = ">=0.103.2"
python-dotenv = ">=1.0.0"
ds-caselaw-marklogic-api-client = ">=5.2.0"
django-environ = ">=0.11.2"
requests = {extras = ["use-chardet-on-py3"], version = ">=2.31.0"}
requests-toolbelt = ">=1.0.0"
lxml = ">= 4.9.3"
httpx = ">= 0.25.0"
uvicorn = ">= 0.23.2"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
