# coding: utf-8

"""
    Case Law Privileged API

    RESTful interface to the Marklogic database

    The version of the OpenAPI document: 0.1.2
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI

from openapi_server.apis.reading_api import router as ReadingApiRouter
from openapi_server.apis.status_api import router as StatusApiRouter
from openapi_server.apis.writing_api import router as WritingApiRouter

app = FastAPI(
    title="Case Law Privileged API",
    description="RESTful interface to the marklogic database",
    version="0.1.2",
)

app.include_router(ReadingApiRouter)
app.include_router(StatusApiRouter)
app.include_router(WritingApiRouter)
