# coding: utf-8

"""
    Case Law Privileged API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.2
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI
from openapi_server.apis.reading_api import router as ReadingApiRouter
from openapi_server.apis.status_api import router as StatusApiRouter
from openapi_server.apis.writing_api import router as WritingApiRouter

app = FastAPI(
    title="Case Law Privileged API",
    description="No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)",
    version="0.1.2",
)

app.include_router(ReadingApiRouter)
app.include_router(StatusApiRouter)
app.include_router(WritingApiRouter)
